### PR TITLE
Save function (DroomOne) and mute shortcut

### PR DESCRIPTION
**Pull request by Round-Pi**
I tested the DroomOne's save function. Besides the in-game clock pausing when not running, it works perfectly.
The Up key simulates pressing both the left and right buttons on the original Tamagotchi (mutes the volume).

### CODE REVIEW

**Comment by RogueMaster** [comment]
Thank you! I copied your mute option 😄

You skipped from your parent to your grand parent... you will likely have better luck at the parent...

**Comment by Round-Pi** [comment]
> Thank you! I copied your mute option 😄
> 
> You skipped from your parent to your grand parent... you will likely have better luck at the parent...

Requesting a pull from the parent now...

**Comment by GMMan** [comment]
I'm working on migrating the app to a view dispatcher/scene based model, so this PR won't be mergeable as is, but the mute button binding is a nice idea. I would probably put mute as an app option in a menu.

**Comment by BricksAndDirt** [comment]
> 

bad at coding, how to get to work?

**Comment by Round-Pi** [comment]
I also created another branch at my fork. It's a the same app but in portrait mode. 
If you're thinking to creating a portrait menu option, feel free to check the branch and skip the maths (I couldn't compile the new sideways icons though). 
I don't know if there's an easier way of doing this that I overlooking.

**Pull request closed without merging**
